version: "3.0"

services:
  centos7.8:
    build: #buildしたときのimage名はimageに指定した名前になる
      context: ./
      dockerfile: Dockerfile
    image: hazuki3417/centos:latest
    container_name: centos
    environment:
      TZ: Asia/Tokyo
    tty: true

networks:
  common_link:
    external: true
