# ワークフロー名
name: Hello, World!

on:
  # actionを起こすイベント名  
  push:
    # イベントのターゲット
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  # jobのid。jobsのキーとしてユニークになるならなんでもいいらしい
  build:
    # jobの名前    
    name: Greeting
    # jobが実行される仮想環境の指定
    runs-on: ubuntu-latest
  
    # job内で実行する処理
    steps:
      - run: echo "Hello, World!!"
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

    # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run: echo Hello, world!

    # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
